// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { LabelDB } from '../label-db'
import { LabelService } from '../label.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-label-sorting',
  templateUrl: './label-sorting.component.html',
  styleUrls: ['./label-sorting.component.css']
})
export class LabelSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Label instances that are in the association
  associatedLabels = new Array<LabelDB>();

  constructor(
    private labelService: LabelService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of label instances
    public dialogRef: MatDialogRef<LabelSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getLabels()
  }

  getLabels(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let label of this.frontRepo.Labels_array) {
          let ID = this.dialogData.ID
          let revPointerID = label[this.dialogData.ReversePointer as keyof LabelDB] as unknown as NullInt64
          let revPointerID_Index = label[this.dialogData.ReversePointer + "_Index" as keyof LabelDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedLabels.push(label)
          }
        }

        // sort associated label according to order
        this.associatedLabels.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedLabels, event.previousIndex, event.currentIndex);

    // set the order of Label instances
    let index = 0

    for (let label of this.associatedLabels) {
      let revPointerID_Index = label[this.dialogData.ReversePointer + "_Index" as keyof LabelDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedLabels.forEach(
      label => {
        this.labelService.updateLabel(label)
          .subscribe(label => {
            this.labelService.LabelServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
