// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { LabelDB } from '../label-db'
import { LabelService } from '../label.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-labelstable',
  templateUrl: './labels-table.component.html',
  styleUrls: ['./labels-table.component.css'],
})
export class LabelsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Label instances
  selection: SelectionModel<LabelDB> = new (SelectionModel)
  initialSelection = new Array<LabelDB>()

  // the data source for the table
  labels: LabelDB[] = []
  matTableDataSource: MatTableDataSource<LabelDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.labels
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (labelDB: LabelDB, property: string) => {
      switch (property) {
        case 'ID':
          return labelDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return labelDB.Name;

        case 'ChartConfiguration_Labels':
          return this.frontRepo.ChartConfigurations.get(labelDB.ChartConfiguration_LabelsDBID.Int64)!.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (labelDB: LabelDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the labelDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += labelDB.Name.toLowerCase()
      if (labelDB.ChartConfiguration_LabelsDBID.Int64 != 0) {
        mergedContent += this.frontRepo.ChartConfigurations.get(labelDB.ChartConfiguration_LabelsDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private labelService: LabelService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of label instances
    public dialogRef: MatDialogRef<LabelsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.labelService.LabelServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getLabels()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "ChartConfiguration_Labels",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "ChartConfiguration_Labels",
      ]
      this.selection = new SelectionModel<LabelDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getLabels()
    this.matTableDataSource = new MatTableDataSource(this.labels)
  }

  getLabels(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.labels = this.frontRepo.Labels_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let label of this.labels) {
            let ID = this.dialogData.ID
            let revPointer = label[this.dialogData.ReversePointer as keyof LabelDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(label)
            }
            this.selection = new SelectionModel<LabelDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, LabelDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as LabelDB[]
          for (let associationInstance of sourceField) {
            let label = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as LabelDB
            this.initialSelection.push(label)
          }

          this.selection = new SelectionModel<LabelDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.labels
      }
    )
  }

  // newLabel initiate a new label
  // create a new Label objet
  newLabel() {
  }

  deleteLabel(labelID: number, label: LabelDB) {
    // list of labels is truncated of label before the delete
    this.labels = this.labels.filter(h => h !== label);

    this.labelService.deleteLabel(labelID).subscribe(
      label => {
        this.labelService.LabelServiceChanged.next("delete")
      }
    );
  }

  editLabel(labelID: number, label: LabelDB) {

  }

  // display label in router
  displayLabelInRouter(labelID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongng2charts_go-" + "label-display", labelID])
  }

  // set editor outlet
  setEditorRouterOutlet(labelID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongng2charts_go_editor: ["github_com_fullstack_lang_gongng2charts_go-" + "label-detail", labelID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(labelID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongng2charts_go_presentation: ["github_com_fullstack_lang_gongng2charts_go-" + "label-presentation", labelID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.labels.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.labels.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<LabelDB>()

      // reset all initial selection of label that belong to label
      for (let label of this.initialSelection) {
        let index = label[this.dialogData.ReversePointer as keyof LabelDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(label)

      }

      // from selection, set label that belong to label
      for (let label of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = label[this.dialogData.ReversePointer as keyof LabelDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(label)
      }


      // update all label (only update selection & initial selection)
      for (let label of toUpdate) {
        this.labelService.updateLabel(label)
          .subscribe(label => {
            this.labelService.LabelServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, LabelDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedLabel = new Set<number>()
      for (let label of this.initialSelection) {
        if (this.selection.selected.includes(label)) {
          // console.log("label " + label.Name + " is still selected")
        } else {
          console.log("label " + label.Name + " has been unselected")
          unselectedLabel.add(label.ID)
          console.log("is unselected " + unselectedLabel.has(label.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let label = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as LabelDB
      if (unselectedLabel.has(label.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<LabelDB>) = new Array<LabelDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          label => {
            if (!this.initialSelection.includes(label)) {
              // console.log("label " + label.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + label.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = label.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = label.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("label " + label.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<LabelDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
