// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ChartConfigurationDB } from './chartconfiguration-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class ChartConfigurationService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ChartConfigurationServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private chartconfigurationsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.chartconfigurationsUrl = origin + '/api/github.com/fullstack-lang/gongng2charts/go/v1/chartconfigurations';
  }

  /** GET chartconfigurations from the server */
  getChartConfigurations(): Observable<ChartConfigurationDB[]> {
    return this.http.get<ChartConfigurationDB[]>(this.chartconfigurationsUrl)
      .pipe(
        tap(_ => this.log('fetched chartconfigurations')),
        catchError(this.handleError<ChartConfigurationDB[]>('getChartConfigurations', []))
      );
  }

  /** GET chartconfiguration by id. Will 404 if id not found */
  getChartConfiguration(id: number): Observable<ChartConfigurationDB> {
    const url = `${this.chartconfigurationsUrl}/${id}`;
    return this.http.get<ChartConfigurationDB>(url).pipe(
      tap(_ => this.log(`fetched chartconfiguration id=${id}`)),
      catchError(this.handleError<ChartConfigurationDB>(`getChartConfiguration id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new chartconfiguration to the server */
  postChartConfiguration(chartconfigurationdb: ChartConfigurationDB): Observable<ChartConfigurationDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    chartconfigurationdb.Datasets = []
    chartconfigurationdb.Labels = []

    return this.http.post<ChartConfigurationDB>(this.chartconfigurationsUrl, chartconfigurationdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted chartconfigurationdb id=${chartconfigurationdb.ID}`)
      }),
      catchError(this.handleError<ChartConfigurationDB>('postChartConfiguration'))
    );
  }

  /** DELETE: delete the chartconfigurationdb from the server */
  deleteChartConfiguration(chartconfigurationdb: ChartConfigurationDB | number): Observable<ChartConfigurationDB> {
    const id = typeof chartconfigurationdb === 'number' ? chartconfigurationdb : chartconfigurationdb.ID;
    const url = `${this.chartconfigurationsUrl}/${id}`;

    return this.http.delete<ChartConfigurationDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted chartconfigurationdb id=${id}`)),
      catchError(this.handleError<ChartConfigurationDB>('deleteChartConfiguration'))
    );
  }

  /** PUT: update the chartconfigurationdb on the server */
  updateChartConfiguration(chartconfigurationdb: ChartConfigurationDB): Observable<ChartConfigurationDB> {
    const id = typeof chartconfigurationdb === 'number' ? chartconfigurationdb : chartconfigurationdb.ID;
    const url = `${this.chartconfigurationsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    chartconfigurationdb.Datasets = []
    chartconfigurationdb.Labels = []

    return this.http.put<ChartConfigurationDB>(url, chartconfigurationdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated chartconfigurationdb id=${chartconfigurationdb.ID}`)
      }),
      catchError(this.handleError<ChartConfigurationDB>('updateChartConfiguration'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
