// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { DataPointDB } from './datapoint-db';

// insertion point for imports
import { DatasetDB } from './dataset-db'

@Injectable({
  providedIn: 'root'
})
export class DataPointService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  DataPointServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private datapointsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.datapointsUrl = origin + '/api/github.com/fullstack-lang/gongng2charts/go/v1/datapoints';
  }

  /** GET datapoints from the server */
  getDataPoints(): Observable<DataPointDB[]> {
    return this.http.get<DataPointDB[]>(this.datapointsUrl)
      .pipe(
        tap(_ => this.log('fetched datapoints')),
        catchError(this.handleError<DataPointDB[]>('getDataPoints', []))
      );
  }

  /** GET datapoint by id. Will 404 if id not found */
  getDataPoint(id: number): Observable<DataPointDB> {
    const url = `${this.datapointsUrl}/${id}`;
    return this.http.get<DataPointDB>(url).pipe(
      tap(_ => this.log(`fetched datapoint id=${id}`)),
      catchError(this.handleError<DataPointDB>(`getDataPoint id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new datapoint to the server */
  postDataPoint(datapointdb: DataPointDB): Observable<DataPointDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let _Dataset_DataPoints_reverse = datapointdb.Dataset_DataPoints_reverse
    datapointdb.Dataset_DataPoints_reverse = new DatasetDB

    return this.http.post<DataPointDB>(this.datapointsUrl, datapointdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        datapointdb.Dataset_DataPoints_reverse = _Dataset_DataPoints_reverse
        this.log(`posted datapointdb id=${datapointdb.ID}`)
      }),
      catchError(this.handleError<DataPointDB>('postDataPoint'))
    );
  }

  /** DELETE: delete the datapointdb from the server */
  deleteDataPoint(datapointdb: DataPointDB | number): Observable<DataPointDB> {
    const id = typeof datapointdb === 'number' ? datapointdb : datapointdb.ID;
    const url = `${this.datapointsUrl}/${id}`;

    return this.http.delete<DataPointDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted datapointdb id=${id}`)),
      catchError(this.handleError<DataPointDB>('deleteDataPoint'))
    );
  }

  /** PUT: update the datapointdb on the server */
  updateDataPoint(datapointdb: DataPointDB): Observable<DataPointDB> {
    const id = typeof datapointdb === 'number' ? datapointdb : datapointdb.ID;
    const url = `${this.datapointsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let _Dataset_DataPoints_reverse = datapointdb.Dataset_DataPoints_reverse
    datapointdb.Dataset_DataPoints_reverse = new DatasetDB

    return this.http.put<DataPointDB>(url, datapointdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        datapointdb.Dataset_DataPoints_reverse = _Dataset_DataPoints_reverse
        this.log(`updated datapointdb id=${datapointdb.ID}`)
      }),
      catchError(this.handleError<DataPointDB>('updateDataPoint'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
