// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { ChartConfigurationDB } from '../chartconfiguration-db'
import { ChartConfigurationService } from '../chartconfiguration.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-chartconfiguration-sorting',
  templateUrl: './chartconfiguration-sorting.component.html',
  styleUrls: ['./chartconfiguration-sorting.component.css']
})
export class ChartConfigurationSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of ChartConfiguration instances that are in the association
  associatedChartConfigurations = new Array<ChartConfigurationDB>();

  constructor(
    private chartconfigurationService: ChartConfigurationService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of chartconfiguration instances
    public dialogRef: MatDialogRef<ChartConfigurationSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getChartConfigurations()
  }

  getChartConfigurations(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let chartconfiguration of this.frontRepo.ChartConfigurations_array) {
          let ID = this.dialogData.ID
          let revPointerID = chartconfiguration[this.dialogData.ReversePointer as keyof ChartConfigurationDB] as unknown as NullInt64
          let revPointerID_Index = chartconfiguration[this.dialogData.ReversePointer + "_Index" as keyof ChartConfigurationDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedChartConfigurations.push(chartconfiguration)
          }
        }

        // sort associated chartconfiguration according to order
        this.associatedChartConfigurations.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedChartConfigurations, event.previousIndex, event.currentIndex);

    // set the order of ChartConfiguration instances
    let index = 0

    for (let chartconfiguration of this.associatedChartConfigurations) {
      let revPointerID_Index = chartconfiguration[this.dialogData.ReversePointer + "_Index" as keyof ChartConfigurationDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedChartConfigurations.forEach(
      chartconfiguration => {
        this.chartconfigurationService.updateChartConfiguration(chartconfiguration)
          .subscribe(chartconfiguration => {
            this.chartconfigurationService.ChartConfigurationServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
